# -------------- Configuration for Elixium Core --------------
[elixium_core]
# Set of peer IPs which is used to make an initial connection to the network
seed_peers = [
  "206.189.103.38:31013",
  "142.93.158.121:31013",
  "142.93.152.227:31013",
  "139.59.13.96:31013"
]

# Path to store elixium related data (blocks, utxos, peers, etc)
data_path = "~/.elixium"

# The port on which to accept inbound connections (must be
# port-forwarded)
port = 31013

# Maximum number of outbound connections. Upon failing to connect
# via outbound request, these will default to accepting inbound
# connections
max_bidirectional_connections = 10

# Maximum number of inbound connections (outside of any
# bidirectional connections that have defaulted to being inbound)
max_inbound_connections = 90

# ------------ End Configuration for Elixium Core ------------

# ------------- Configuration for Elixium Miner --------------
[elixium_miner]
# Elixium address which to credit block rewards to
address = ""

# Enable/disable RPC
rpc = false

# Which port to run RPC on (if enabled)
rpc_port = 32123

# Number of mining processes to spawn. Set to "dynamic" to allocate
# one process per CPU core (usually resulting in best performance),
# or set to an integer
mining_processes = "dynamic"

[logger.info]
level = "info"
path = "./log/info.log"
