# -------------- Configuration for Elixium Core --------------
[elixium_core]
# Set of peer IPs which is used to make an initial connection to the network
seed_peers = [
  "207.246.94.61:31013",
  "45.77.203.34:31013",
  "173.199.124.10:31013",
  "149.28.35.185:31013",
  "149.28.45.175:31013",
  "207.246.125.167:31013",
  "149.28.38.82:31013",
  "144.202.29.48:31013"
]

# Path to store elixium related data (blocks, utxos, peers, etc)
data_path = "~/.elixium"

# The port on which to accept inbound connections (must be
# port-forwarded)
port = 31013

# Maximum number of connections to peers.
max_connections = 10

# ------------ End Configuration for Elixium Core ------------

# ------------- Configuration for Elixium Miner --------------
[elixium_miner]
# Elixium address which to credit block rewards to
address = ""

# Enable/disable RPC
rpc = false

# Which port to run RPC on (if enabled)
rpc_port = 32123

# Number of mining processes to spawn. Set to "dynamic" to allocate
# one process per CPU core (usually resulting in best performance),
# or set to an integer
mining_processes = "dynamic"

[logger.info]
level = "info"
path = "./log/info.log"
